### ISSUE TITLE
npm start is failing after upgrade ui5/cli from 2.9.3 to 2.10.2

### ISSUE THREAD

**Issue by sanjoy0308** [SAP/ui5-tooling#509]
## Expected Behavior
It should open flpsandbox.html in the browser

## Current Behavior
I receive this error in console

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'update-notifier'
Require stack:
- C:\Users\user\VSCode\userdata\node_modules\@ui5\cli\bin\ui5.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Timeout._onTimeout (C:\Users\user\VSCode\userdata\node_modules\@ui5\cli\bin\ui5.js:46:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\VSCode\\userdata\\node_modules\\@ui5\\cli\\bin\\ui5.js'
  ]
}
```

## Steps to Reproduce the Issue
1. I start npm start and received message to upgrade and I upgraded ui5/cli
2. After upgradation, I get the error
3. If I switch back to 2.9.3, then npm start is working again

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): 2.10.2
 * Node.js Version: 12.18.2
 * npm Version: 7.6.1
 * OS/Platform: Windows 10
 * Browser *(if relevant)*: chrome
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
```
PS C:\Users\user\VSCode\userdata> npm start --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'start',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.6.1
npm info using node@v12.18.2
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\user\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\user\VSCode\userdata\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\user\.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:C:\Users\user\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 9ms
npm verb npm-session f7a51b29ec528bbb
npm timing npm:load Completed in 30ms

> userdata@1.0.0 start
> ui5 serve -o test/flpSandbox.html

internal/modules/cjs/loader.js:969m:load Completed in 30ms
  throw err;
  ^

Error: Cannot find module 'update-notifier'
Require stack:
- C:\Users\user\VSCode\userdata\node_modules\@ui5\cli\bin\ui5.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Timeout._onTimeout (C:\Users\user\VSCode\userdata\node_modules\@ui5\cli\bin\ui5.js:46:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\VSCode\\userdata\\node_modules\\@ui5\\cli\\bin\\ui5.js'
  ]
}
npm timing command:run-script Completed in 186ms
npm timing command:start Completed in 199ms
npm verb exit 1
npm timing npm Completed in 434ms
npm verb code 1
```

**Comment by RandomByte** [comment]
Hi @sanjoy0308, Thanks for reporting. Apparently I was not able to reproduce this behavior with the [openui5-sample-app](https://github.com/SAP/openui5-sample-app) and Node.js 12.18.2/npm 7.6.1.

In general, npm should take care of installing the `update-notifier` dependency correctly.

However, we got similar reports recently. **In those cases it apparently helped to reinstall the CLI once again. If you have ever installed it globally, try reinstalling it globally as well (`npm i -g @ui5/cli`).**

Please let us know whether that also resolves your issue.

Since all reports mention npm v7 to be used, I'm starting to believe this might be a side effect from upgrading npm v6 to v7.

**Comment by sanjoy0308** [comment]
After I reinstalled npm i -g @ui5/cli, it is working. Thank you @RandomByte

**Comment by RandomByte** [comment]
Thanks for the feedback! Glad it's working now.

We'll keep an eye on this topic.
